# =========================
# NovaSides
# =========================

border-x: 0

border:
  enabled: true

markers:
  enabled: true
  spacing: 500

particles:
  enabled: true
  distance: 10

actionbar:
  enabled: true

generation:
  min-z: -5000
  max-z: 5000

spawn:
  world: world
  x: 0
  y: 100
  z: 0
  yaw: 0
  pitch: 0
